### PR TITLE
Osc change files

### PR DESCRIPTION
**Pull request by tsmock**
### Description:

Followup of #743 and #746.

Add an option (`-keepAll` set in osmlab/atlas-generator) to be used when generating an Atlas file for QC/QA purposes. This prevents the removal of non-tagged nodes.

### Potential Impact:

In order to create geometry changes for MapRoulette, osmlab/atlas-checks needs to know the OSM ids of the nodes of the way.

The atlas files _will_ be larger.

### Unit Test Approach:

The OSC output information is checked against expected OSC output information.

### Test Results:

This does increase file sizes (files generated with https://github.com/osmlab/atlas-generator/pull/179 ).

| File | Original Size | New Size |
|-----|-------------|-----------|
| USA_10-202-390.atlas | 2 MB | 6.2 MB |
| USA_10-202-391.atlas | 1 MB | 3.0 MB |
| USA_10-203-390.atlas | 2.1 MB | 6.5 MB |
| USA_10-203-390.atlas | 5.5 MB | 14 MB |

Performance testing is in progress, but the boolean check in [FeatureChange#withAtlasContext](https://github.com/osmlab/atlas/pull/750/files#diff-2df018462472e8081fa90f3b11cd67d56ac1eb1727460e3a713541dd3ce1c464R740) did improve run time.

### CODE REVIEW

**Comment by tsmock** [comment]
Pinging @Bentleysb and @jwpgage for a preliminary review -- I've got to fix the import ordering issue (`spotlessApply` doesn't help, so I'm having to move the failing import around), but I don't forsee any major changes to the code at this time.

**Comment by atiannicelli** [comment]
Any update on the review of this PR @Bentleysb @jwpgage ?

**Comment by tsmock** [comment]
I've done a run with the following characteristics in `atlas-generator`:

In `gradle.properties`:
```
profile=local.sgs

generator.local.sgs.mainClass=org.openstreetmap.atlas.generator.AtlasGenerator
generator.local.sgs.input=file://@BUILDDIR@/../pbf
generator.local.sgs.output=file://@BUILDDIR@/example/output/
generator.local.sgs.countries=SGS
generator.local.sgs.countryShapes=file://@BUILDDIR@/../pbf/osm_world_boundaries.txt.gz
generator.local.sgs.pbfs=file://@BUILDDIR@/../pbf
generator.local.sgs.pbfScheme=zz/xx/yy/zz-xx-yy.pbf
generator.local.sgs.sharding=dynamic@file://@BUILDDIR@/../pbf/sharding.txt
generator.local.sgs.compressOutput=false
generator.local.sgs.keep-intermediate=true
generator.local.sgs.keepAll=true
generator.local.sgs.startedFolder=file://@BUILDDIR@/example/tmp/
generator.local.sgs.cluster=local
generator.local.sgs.sparkOptions=spark.executor.memory->4g,spark.driver.memory->4g,spark.rdd.compress->true
```
In `gradle/execution.gradle`:
```
    jvmArgs(["-Xmx4g","-Xms4g", "-XX:+HeapDumpOnOutOfMemoryError", "-XX:HeapDumpPath=build/"])
```


100 runs for my local `dev` (untouched) branch and the osc branch were done with the following command on each branch:
`for i in `seq 100`; do (time ./gradlew clean run) 2>> time.txt; done`

Results (after processing):

  | function | time type | osc | dev
-- | -- | -- | -- | --
  | STDEV | user | 0.23 | 0.21
  | STDEV | system | 0.04 | 0.07
  | STDEV | cpu | 0.40% | 0.35%
  | STDEV | total | 00:00:09 | 00:00:08
  | average | user | 1.95 | 1.96
  | average | system | 0.28 | 0.28
  | average | cpu | 2.20% | 2.96%
  | average | total | 00:01:17 | 00:01:04
  | min | user | 1.68 | 1.67
  | min | system | 0.22 | 0.20
  | min | cpu | 2.00% | 2.00%
  | min | total | 00:01:03 | 00:00:52
  | max | user | 2.94 | 2.88
  | max | system | 0.45 | 0.51
  | max | cpu | 3.00% | 4.00%
  | max | total | 00:02:08 | 00:01:34
90.00% | Percentile | user | 2.23 | 2.20
90.00% | Percentile | system | 0.32 | 0.35
90.00% | Percentile | cpu | 3.00% | 3.00%
90.00% | Percentile | total | 00:01:24 | 00:01:16
10.00% | Percentile | user | 1.77 | 1.74
10.00% | Percentile | system | 0.23 | 0.23
10.00% | Percentile | cpu | 2.00% | 3.00%
10.00% | Percentile | total | 00:01:10 | 00:00:56


So, once the outliers are removed (see differences in 10% and 90% percentiles), it looks like there are no significant runtime differences for small areas, at least for user/system CPU time. Wall clock time did vary (min difference ~11s, max difference ~34s, average difference ~13s, 10% percentile difference ~14s, 90% percentile difference ~8s).

I'll continue trying to get a larger area to run, but we'll see how that pans out.

**Comment by tsmock** [comment]
Code smells:
* 4 for duplicate code blocks. I don't see a good way to deduplicate them, since I need to extend the appropriate Atlas entity type.
* 4 for using equals to verify that the equals method works. I didn't see

**Comment by atiannicelli** [comment]
Please see characteristics see when running with and without this new code. Also with the keepall flag off (default) and on.
https://github.com/osmlab/atlas-generator/pull/179#issuecomment-915488679

**Comment by jwpgage** [comment]
PR looks ready for merge, but first please resolve merge conflicts

**Comment by tsmock** [comment]
I've resolved the merge conflicts.

Updates on code smells:
* 4 for duplicate code blocks. I don't see a good way to deduplicate them, since I need to extend the appropriate Atlas entity type.
* 4 for using equals to verify that the equals method works. I didn't see anything truly testing the equals method. Probably the best route would be to use an EqualsVerifier (e.g. https://github.com/jqno/equalsverifier , which is what JOSM uses).
* 2 for returning `null` instead of an empty collection. This is due to the methods returning a `PolyLine`, which has no empty representation thereof (last I checked, [`PolyLine`](https://github.com/osmlab/atlas/blob/0698ee731af91498139cd29230a9f729aa7e7f19/src/main/java/org/openstreetmap/atlas/geography/PolyLine.java#L146) threw if there were no points).

**Review by jwpgage — APPROVED** [review]

**Pull request merged**
