### PR TITLE
Catch way-sectioning errors

### PR DESCRIPTION
**Pull request by matthieun**
### Description:

This is to catch way-sectioning errors that might come from corrupted data, before a whole way-sectioning process has to fail. The Lines that cannot be way-sectioned are logged and then dropped.

### Potential Impact:

More way-sectioning jobs can go through without failing. However that increases the risk of dropping large amounts of data in case a future underlying bug is introduced and the way-sectioning process does not fail.

### Unit Test Approach:

Added new test, with specific OSM data.

### Test Results:

Pass

------

In doubt: [Contributing Guidelines](CONTRIBUTING.md)

### CODE REVIEW

**Comment by MikeGost** [comment]
Miss this code! Where kind of corrupt data was it?

**Comment by matthieun** [comment]
The issue is with this OSM way that was recently deleted! https://www.openstreetmap.org/way/858888726/history
```
LINESTRING (49.9933986 14.9056073, 49.9933775 14.9053719, 49.9929567 14.9054263, 49.9933775 14.9053719, 49.9933986 14.9056073, 49.9933775 14.9053719, 49.9933986 14.9056073)
```
Does not look like it, but it overlaps itself in many places!
image

**Comment by matthieun** [comment]
Looks like it was just replaced by this one: https://www.openstreetmap.org/way/864587512

**Comment by MikeGost** [comment]
Oh interesting! I remember seeing similar junk when testing this logic, glad it was cleaned up!

**Comment by matthieun** [comment]
Fixed code smells. Seems the duplication was pre-existing, so leaving that...

**Review by adahn6 — APPROVED** [review]

**Pull request merged**
