### PR TITLE
Add sonar integration

### PR DESCRIPTION
**Pull request by matthieun**
This simple update to the travis scripts add support for running sonar reports during CRON builds. The results will be available in the [Sonar osmlab project](https://sonarcloud.io/organizations/osmlab/projects):

Here is how a sample run looks like:

image

### CODE REVIEW

**Comment by lucaspcram** [comment]
Looks awesome! But it really doesn't like the autogenerated code...

**Comment by matthieun** [comment]
Yep. Next step is to go deeper and understand how to skip some parts of the codebase.

**Comment by lucaspcram** [comment]
I'm actually pretty interested in looking into this. I'll investigate a little tomorrow and see if there is any Sonar documentation on it.

**Comment by lucaspcram** [comment]
Here's an update to force Sonar to exclude the autogenerated code.

In `build.gradle` right below the `protobuf` configuration block, add the following code block:

```
sonarqube {
    properties {
        property "sonar.exclusions", "src/generated/**/*.java"
    }
}
```

**Pull request merged**
